### ISSUE TITLE
`Notification::getTransactionReference()` powinno wskazywać na `externalId`

### ISSUE THREAD

**Issue by pszalko** [pay-now/omnipay-paynow#8]
W klasie `Message/Notification` metoda `getTransactionReference()` wskazuje na `paymentId` który jest identyfikatorem płatności w systemie PayNow zamiast na `externalId` który jest identyfikatorem płatności w systemie klienta.

Odbierając powiadomienie w obecnej formie, jako klient, nie można nic z nim zrobić, ponieważ nie ma jak odczytać identyfikatora płatności w lokalnym systemie wykorzystując interfejs Omnipay.

Oczywiście można pobrać `externalId` poprzez `getData()`, ale wtedy dla każdego dostawcy trzeba będzie modyfikować kod do odbioru powiadomienia.

Podsumowując, wydaje mi się że metoda `getTransactionReference()` powinna zwracać wartość `externalId` zamiast `paymentId`.

**Comment by michalskladanowski** [comment]
Zgodnie z [dokumentacją OmniPay ](https://omnipay.thephpleague.com/gateways/build-your-own/):
`transactionReference is the Payment Gateway’s reference to the transaction. They will usually generate a unique reference for each payment attempt a customer makes. It is common practice to store this value in the Merchant Site’s database, so that the transaction can be cross-referenced with the Payment Gateway’s own records. Some Omnipay drivers also rely on this value being available in order to process refunds or repeat payments.`

transactionReference powinno wskazywać na identyfikator transakcji po stronie systemu płatności.

**Comment by pszalko** [comment]
Ok, zgadza się :)

Przegapiłem że w `PurchaseResponse` dostajemy też `transactionReference` który możemy od razu zapamiętać. 

Dzięki!
